# Generated by Django 5.2.1 on 2025-05-12 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='stall',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='stall',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='stall',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('cooking_time', models.PositiveIntegerField(help_text='Cooking time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='orders.stall')),
            ],
        ),
    ]
